### FAÇA VOCE MESMO

# CRIAR DOIS NOVOS DICIONARIOS QUE  REPRESENTEM PESSOAS DIFERENTE E ARMAZENE EM UM DICIONARIO
# ARMAZENE OS TRES DICIONARIOS EM UMA LISTA CHAMADA people. PERCORRA SUA LISTA DE PESSOAS COM UM LAÇO.
# A MEDIDA QUE PERCORRER A LISTA APRESENTE TUDO QUE VOCÊ SABE SOBRE CADA PESSOA

