### CRIAR UM DICIONARIO ONDE NOME DOS DICIONARIOS SÃO OS NOMES DOS PETS
### EM CADA DICIONARIO INCLUA O TIPO DO ANIMAL E NOME DO DONO
### ARMAZENE EM UMA LISTA CHAMADA PETS
### PERCORRER LISTA COM LAÇO MOSTRANDO INFORMAÇÕES

cachorro = {
        
}
