### A FUNÇÃO input() É UTILIZADA PARA SOLICATAR UMA ENTRADA DO USUÁRIO
### UTILIZAMOS UMA VARIÁVEL PARA GUARDAR O VALOR DIGITADO PELO USUÁRIO

variavel = input('Digite qualquer coisa: ')             # SOLICITA AO USUARIO UMA ENTRADA E GUARDA NA VARIAVEL variavel
print(variavel)

### A FUNÇÃO input() COLETA O A ENTRADA DO USUARIO SEMPRE EM STRING srt() E PARA TRANSFORMAR EM NUMERO USAMOS int() 
print('-'*50)


